class Disease:
    def __init__(self, transmission_rate: float, fatality_rate: float, days_in_incubation: int, days_with_symptoms: int, name: str = "") -> None: ...

    @property
    def transmission_rate(self) -> float: ...

    @property
    def fatality_rate(self) -> float: ...

    @property
    def days_in_incubation(self) -> int: ...

    @property
    def days_with_symptoms(self) -> int: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, name: str) -> None: ...
